data:
  database:
    driver: "mysql"
    source: "tcp://localhost:9004?database=default&read_timeout=10&write_timeout=20"
    migrate: true

  redis:
    addr: "localhost:6379"
    dial_timeout: 10s
    read_timeout: 0.4s
    write_timeout: 0.6s