// Code generated by ent, DO NOT EDIT.

package realtimewarehousing

const (
	// Label holds the string label denoting the realtimewarehousing type in the database.
	Label = "realtime_warehousing"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEventName holds the string denoting the event_name field in the database.
	FieldEventName = "event_name"
	// FieldReportData holds the string denoting the report_data field in the database.
	FieldReportData = "report_data"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// Table holds the table name of the realtimewarehousing in the database.
	Table = "realtime_warehousing"
)

// Columns holds all SQL columns for realtimewarehousing fields.
var Columns = []string{
	FieldID,
	FieldEventName,
	FieldReportData,
	FieldCreateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventNameValidator is a validator for the "event_name" field. It is called by the builders before save.
	EventNameValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)
