data:
  database:
    driver: "clickhouse"
    source: "clickhouse://localhost:9000/default?dial_timeout=200ms&max_execution_time=60"

  redis:
    addr: "localhost:6379"
    dial_timeout: 10s
    read_timeout: 0.4s
    write_timeout: 0.6s