server:
  grpc:
    addr: "0.0.0.0:0"
    timeout: 10s
    middleware:

  kafka:
    codec: "json"
    addrs:
      - "host.docker.internal:9092"

client:
  grpc:
    timeout: 10s
    middleware:
      enable_logging: true
      enable_recovery: true
      enable_tracing: true
      enable_validate: true
      enable_circuit_breaker: true
      auth:
        method: ""
        key: "some_api_key"
