// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
	"kratos-bi/app/admin/service/internal/biz"
	"kratos-bi/app/admin/service/internal/data"
	"kratos-bi/app/admin/service/internal/server"
	"kratos-bi/app/admin/service/internal/service"
	"kratos-bi/gen/api/go/common/conf"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(logger log.Logger, registrar registry.Registrar, bootstrap *conf.Bootstrap) (*kratos.App, func(), error) {
	authenticator := data.NewAuthenticator(bootstrap)
	engine := data.NewAuthorizer()
	discovery := data.NewDiscovery(bootstrap)
	userServiceClient := data.NewUserServiceClient(discovery, bootstrap)
	userService := service.NewUserService(userServiceClient, logger)
	client := data.NewRedisClient(bootstrap, logger)
	applicationServiceClient := data.NewApplicationServiceClient(discovery, bootstrap)
	dataData, cleanup, err := data.NewData(logger, client, authenticator, engine, userServiceClient, applicationServiceClient)
	if err != nil {
		return nil, nil, err
	}
	userTokenRepo := data.NewUserTokenRepo(dataData, authenticator, logger)
	userTokenUseCase := biz.NewUserAuthUseCase(userTokenRepo)
	authenticationService := service.NewAuthenticationService(logger, userServiceClient, userTokenUseCase)
	applicationService := service.NewApplicationService(logger, applicationServiceClient)
	httpServer := server.NewHTTPServer(bootstrap, logger, authenticator, engine, userService, authenticationService, applicationService)
	app := newApp(logger, registrar, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
