// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kratos-bi/app/report/service/internal/data/ent/predicate"
	"kratos-bi/app/report/service/internal/data/ent/realtimewarehousing"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RealtimeWarehousingQuery is the builder for querying RealtimeWarehousing entities.
type RealtimeWarehousingQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.RealtimeWarehousing
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RealtimeWarehousingQuery builder.
func (rwq *RealtimeWarehousingQuery) Where(ps ...predicate.RealtimeWarehousing) *RealtimeWarehousingQuery {
	rwq.predicates = append(rwq.predicates, ps...)
	return rwq
}

// Limit the number of records to be returned by this query.
func (rwq *RealtimeWarehousingQuery) Limit(limit int) *RealtimeWarehousingQuery {
	rwq.ctx.Limit = &limit
	return rwq
}

// Offset to start from.
func (rwq *RealtimeWarehousingQuery) Offset(offset int) *RealtimeWarehousingQuery {
	rwq.ctx.Offset = &offset
	return rwq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rwq *RealtimeWarehousingQuery) Unique(unique bool) *RealtimeWarehousingQuery {
	rwq.ctx.Unique = &unique
	return rwq
}

// Order specifies how the records should be ordered.
func (rwq *RealtimeWarehousingQuery) Order(o ...OrderFunc) *RealtimeWarehousingQuery {
	rwq.order = append(rwq.order, o...)
	return rwq
}

// First returns the first RealtimeWarehousing entity from the query.
// Returns a *NotFoundError when no RealtimeWarehousing was found.
func (rwq *RealtimeWarehousingQuery) First(ctx context.Context) (*RealtimeWarehousing, error) {
	nodes, err := rwq.Limit(1).All(setContextOp(ctx, rwq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{realtimewarehousing.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rwq *RealtimeWarehousingQuery) FirstX(ctx context.Context) *RealtimeWarehousing {
	node, err := rwq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RealtimeWarehousing ID from the query.
// Returns a *NotFoundError when no RealtimeWarehousing ID was found.
func (rwq *RealtimeWarehousingQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = rwq.Limit(1).IDs(setContextOp(ctx, rwq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{realtimewarehousing.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rwq *RealtimeWarehousingQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := rwq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RealtimeWarehousing entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RealtimeWarehousing entity is found.
// Returns a *NotFoundError when no RealtimeWarehousing entities are found.
func (rwq *RealtimeWarehousingQuery) Only(ctx context.Context) (*RealtimeWarehousing, error) {
	nodes, err := rwq.Limit(2).All(setContextOp(ctx, rwq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{realtimewarehousing.Label}
	default:
		return nil, &NotSingularError{realtimewarehousing.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rwq *RealtimeWarehousingQuery) OnlyX(ctx context.Context) *RealtimeWarehousing {
	node, err := rwq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RealtimeWarehousing ID in the query.
// Returns a *NotSingularError when more than one RealtimeWarehousing ID is found.
// Returns a *NotFoundError when no entities are found.
func (rwq *RealtimeWarehousingQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = rwq.Limit(2).IDs(setContextOp(ctx, rwq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{realtimewarehousing.Label}
	default:
		err = &NotSingularError{realtimewarehousing.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rwq *RealtimeWarehousingQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := rwq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RealtimeWarehousings.
func (rwq *RealtimeWarehousingQuery) All(ctx context.Context) ([]*RealtimeWarehousing, error) {
	ctx = setContextOp(ctx, rwq.ctx, "All")
	if err := rwq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RealtimeWarehousing, *RealtimeWarehousingQuery]()
	return withInterceptors[[]*RealtimeWarehousing](ctx, rwq, qr, rwq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rwq *RealtimeWarehousingQuery) AllX(ctx context.Context) []*RealtimeWarehousing {
	nodes, err := rwq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RealtimeWarehousing IDs.
func (rwq *RealtimeWarehousingQuery) IDs(ctx context.Context) (ids []uint32, err error) {
	if rwq.ctx.Unique == nil && rwq.path != nil {
		rwq.Unique(true)
	}
	ctx = setContextOp(ctx, rwq.ctx, "IDs")
	if err = rwq.Select(realtimewarehousing.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rwq *RealtimeWarehousingQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := rwq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rwq *RealtimeWarehousingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rwq.ctx, "Count")
	if err := rwq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rwq, querierCount[*RealtimeWarehousingQuery](), rwq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rwq *RealtimeWarehousingQuery) CountX(ctx context.Context) int {
	count, err := rwq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rwq *RealtimeWarehousingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rwq.ctx, "Exist")
	switch _, err := rwq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rwq *RealtimeWarehousingQuery) ExistX(ctx context.Context) bool {
	exist, err := rwq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RealtimeWarehousingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rwq *RealtimeWarehousingQuery) Clone() *RealtimeWarehousingQuery {
	if rwq == nil {
		return nil
	}
	return &RealtimeWarehousingQuery{
		config:     rwq.config,
		ctx:        rwq.ctx.Clone(),
		order:      append([]OrderFunc{}, rwq.order...),
		inters:     append([]Interceptor{}, rwq.inters...),
		predicates: append([]predicate.RealtimeWarehousing{}, rwq.predicates...),
		// clone intermediate query.
		sql:  rwq.sql.Clone(),
		path: rwq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime int64 `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RealtimeWarehousing.Query().
//		GroupBy(realtimewarehousing.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rwq *RealtimeWarehousingQuery) GroupBy(field string, fields ...string) *RealtimeWarehousingGroupBy {
	rwq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RealtimeWarehousingGroupBy{build: rwq}
	grbuild.flds = &rwq.ctx.Fields
	grbuild.label = realtimewarehousing.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime int64 `json:"create_time,omitempty"`
//	}
//
//	client.RealtimeWarehousing.Query().
//		Select(realtimewarehousing.FieldCreateTime).
//		Scan(ctx, &v)
func (rwq *RealtimeWarehousingQuery) Select(fields ...string) *RealtimeWarehousingSelect {
	rwq.ctx.Fields = append(rwq.ctx.Fields, fields...)
	sbuild := &RealtimeWarehousingSelect{RealtimeWarehousingQuery: rwq}
	sbuild.label = realtimewarehousing.Label
	sbuild.flds, sbuild.scan = &rwq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RealtimeWarehousingSelect configured with the given aggregations.
func (rwq *RealtimeWarehousingQuery) Aggregate(fns ...AggregateFunc) *RealtimeWarehousingSelect {
	return rwq.Select().Aggregate(fns...)
}

func (rwq *RealtimeWarehousingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rwq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rwq); err != nil {
				return err
			}
		}
	}
	for _, f := range rwq.ctx.Fields {
		if !realtimewarehousing.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rwq.path != nil {
		prev, err := rwq.path(ctx)
		if err != nil {
			return err
		}
		rwq.sql = prev
	}
	return nil
}

func (rwq *RealtimeWarehousingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RealtimeWarehousing, error) {
	var (
		nodes = []*RealtimeWarehousing{}
		_spec = rwq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RealtimeWarehousing).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RealtimeWarehousing{config: rwq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(rwq.modifiers) > 0 {
		_spec.Modifiers = rwq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rwq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rwq *RealtimeWarehousingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rwq.querySpec()
	if len(rwq.modifiers) > 0 {
		_spec.Modifiers = rwq.modifiers
	}
	_spec.Node.Columns = rwq.ctx.Fields
	if len(rwq.ctx.Fields) > 0 {
		_spec.Unique = rwq.ctx.Unique != nil && *rwq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rwq.driver, _spec)
}

func (rwq *RealtimeWarehousingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(realtimewarehousing.Table, realtimewarehousing.Columns, sqlgraph.NewFieldSpec(realtimewarehousing.FieldID, field.TypeUint32))
	_spec.From = rwq.sql
	if unique := rwq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rwq.path != nil {
		_spec.Unique = true
	}
	if fields := rwq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, realtimewarehousing.FieldID)
		for i := range fields {
			if fields[i] != realtimewarehousing.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rwq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rwq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rwq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rwq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rwq *RealtimeWarehousingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rwq.driver.Dialect())
	t1 := builder.Table(realtimewarehousing.Table)
	columns := rwq.ctx.Fields
	if len(columns) == 0 {
		columns = realtimewarehousing.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rwq.sql != nil {
		selector = rwq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rwq.ctx.Unique != nil && *rwq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range rwq.modifiers {
		m(selector)
	}
	for _, p := range rwq.predicates {
		p(selector)
	}
	for _, p := range rwq.order {
		p(selector)
	}
	if offset := rwq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rwq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rwq *RealtimeWarehousingQuery) Modify(modifiers ...func(s *sql.Selector)) *RealtimeWarehousingSelect {
	rwq.modifiers = append(rwq.modifiers, modifiers...)
	return rwq.Select()
}

// RealtimeWarehousingGroupBy is the group-by builder for RealtimeWarehousing entities.
type RealtimeWarehousingGroupBy struct {
	selector
	build *RealtimeWarehousingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rwgb *RealtimeWarehousingGroupBy) Aggregate(fns ...AggregateFunc) *RealtimeWarehousingGroupBy {
	rwgb.fns = append(rwgb.fns, fns...)
	return rwgb
}

// Scan applies the selector query and scans the result into the given value.
func (rwgb *RealtimeWarehousingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rwgb.build.ctx, "GroupBy")
	if err := rwgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RealtimeWarehousingQuery, *RealtimeWarehousingGroupBy](ctx, rwgb.build, rwgb, rwgb.build.inters, v)
}

func (rwgb *RealtimeWarehousingGroupBy) sqlScan(ctx context.Context, root *RealtimeWarehousingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rwgb.fns))
	for _, fn := range rwgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rwgb.flds)+len(rwgb.fns))
		for _, f := range *rwgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rwgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rwgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RealtimeWarehousingSelect is the builder for selecting fields of RealtimeWarehousing entities.
type RealtimeWarehousingSelect struct {
	*RealtimeWarehousingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rws *RealtimeWarehousingSelect) Aggregate(fns ...AggregateFunc) *RealtimeWarehousingSelect {
	rws.fns = append(rws.fns, fns...)
	return rws
}

// Scan applies the selector query and scans the result into the given value.
func (rws *RealtimeWarehousingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rws.ctx, "Select")
	if err := rws.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RealtimeWarehousingQuery, *RealtimeWarehousingSelect](ctx, rws.RealtimeWarehousingQuery, rws, rws.inters, v)
}

func (rws *RealtimeWarehousingSelect) sqlScan(ctx context.Context, root *RealtimeWarehousingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rws.fns))
	for _, fn := range rws.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rws.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rws *RealtimeWarehousingSelect) Modify(modifiers ...func(s *sql.Selector)) *RealtimeWarehousingSelect {
	rws.modifiers = append(rws.modifiers, modifiers...)
	return rws
}
