// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"kratos-uba/app/core/service/internal/data/ent/debugdevice"
	"kratos-uba/app/core/service/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DebugDeviceDelete is the builder for deleting a DebugDevice entity.
type DebugDeviceDelete struct {
	config
	hooks    []Hook
	mutation *DebugDeviceMutation
}

// Where appends a list predicates to the DebugDeviceDelete builder.
func (ddd *DebugDeviceDelete) Where(ps ...predicate.DebugDevice) *DebugDeviceDelete {
	ddd.mutation.Where(ps...)
	return ddd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ddd *DebugDeviceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ddd.sqlExec, ddd.mutation, ddd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ddd *DebugDeviceDelete) ExecX(ctx context.Context) int {
	n, err := ddd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ddd *DebugDeviceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(debugdevice.Table, sqlgraph.NewFieldSpec(debugdevice.FieldID, field.TypeUint32))
	if ps := ddd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ddd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ddd.mutation.done = true
	return affected, err
}

// DebugDeviceDeleteOne is the builder for deleting a single DebugDevice entity.
type DebugDeviceDeleteOne struct {
	ddd *DebugDeviceDelete
}

// Where appends a list predicates to the DebugDeviceDelete builder.
func (dddo *DebugDeviceDeleteOne) Where(ps ...predicate.DebugDevice) *DebugDeviceDeleteOne {
	dddo.ddd.mutation.Where(ps...)
	return dddo
}

// Exec executes the deletion query.
func (dddo *DebugDeviceDeleteOne) Exec(ctx context.Context) error {
	n, err := dddo.ddd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{debugdevice.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dddo *DebugDeviceDeleteOne) ExecX(ctx context.Context) {
	if err := dddo.Exec(ctx); err != nil {
		panic(err)
	}
}
